### ISSUE TITLE
Meshes with more than 65535 verticies (that need 32-bit index buffer) not supported?

### ISSUE THREAD

**Issue by Derzo** [jkuhlmann/cgltf#111]
When I load a mesh with more than 65535 verticies, cgltf discards all the extra verticies. The *indices* structs *component_type* stays at *cgltf_component_type_r_16u* and the position attribute structs *count* says 65535.

GLTF does support more than 65545 verticies, for example when I export and import back such a mesh in blender, it all works. Are you planning on making this work?

**Comment by zeux** [comment]
Do you have an example .gltf file? This works fine for me. component_type in particular is read from the .gltf componentType so if that uses a UNSIGNED_INT index type, you should get r_32u.

**Comment by Derzo** [comment]
Hmm, that's interesting. I don't see why it wouldn't work for me then. Here you go
[gltftest.zip](https://github.com/jkuhlmann/cgltf/files/4464194/gltftest.zip)

![image](https://user-images.githubusercontent.com/16746615/79038049-fe710f80-7bde-11ea-9f62-f3972391247f.png)

![image](https://user-images.githubusercontent.com/16746615/79038056-0df05880-7bdf-11ea-8f2b-3a7d65b9f9ac.png)

**Comment by zeux** [comment]
Your glTF file doesn't use 32-bit indices. The mesh has 3 primitives, with 291552 indices & 65535 vertices in the first, 274953 indices & 61834 vertices in the second, and 213 indices & 89 vertices in the third one (you can see this by inspecting the gltf file, particularly the meshes and accessors used).

So cgltf correctly returns *three* primitives - it's up to your application to either decide to merge them or decide to keep them split and use 16-bit indices.

**Comment by Derzo** [comment]
Oh, I see. I should have read the spec, my bad.
