### ISSUE TITLE
missing transmission term

### ISSUE THREAD

**Issue by seanbaxter** [jkuhlmann/cgltf#123]
cgltf_transmission is missing the refraction term "ior."

https://github.com/KhronosGroup/glTF/blob/d3068171cc56a97b2fc488f407636b8d818d336f/extensions/2.0/Vendor/ADOBE_materials_thin_transparency/README.md#properties

**Comment by prideout** [comment]
I don't understand; cgltf does not support that particular ADOBE extension.   Note however that it supports KHR_materials_transmission, and that KHR_materials_ior is on the way via PR 122.

**Comment by seanbaxter** [comment]
KHR_materials_transmission isn't in the glTF repository. I didn't know that existed and thought the transmission stuff was the ADOBE extension, which is in the repo. Sorry.

**Comment by prideout** [comment]
No worries.  [KHR_materials_transmission ](https://github.com/KhronosGroup/glTF/pull/1698)is part of the "PBR next" effort that the glTF specifiers are working on.  It is already supported by Babylon, and ThreeJS and Filament.
