### ISSUE TITLE
Deeper file validation

### ISSUE THREAD

**Issue by mosra** [jkuhlmann/cgltf#14]
This is moving the discussion from #6, incorporating the points from @zeux as well. The idea is to provide two separate validation levels:

- [ ] Checking for basic file validity during `cgltf_parse()`. The goal of ensuring the user code can trust basic data pointers/ranges and indices in the imported data structures, while keeping these checks efficient enough to avoid significant slowdown of import time. In particular:

    - Ensuring all attributes required by the specs are present (or is this already done?)
    - Ensuring all data ranges in accessors, buffer views and buffers are in bounds of the actual buffer (this is one thing that tinygltf doesn't do and it's one of the main pain points as the user code has to check explicitly on each access)
    - Ensuring node, material, mesh, animation, ... indices are in bounds as well
    - Anything else?
     
    All those checks need only access to the JSON file (not to the data buffers). Failure in any those checks would result in a hard parse error.

- [ ] Providing further validation via a hypothetical new `cgltf_validate()` API. Goal of this API is deeper validation (maybe in-line with what the official online [glTF Validator](http://github.khronos.org/glTF-Validator/) does?), having mainly checks that would be slow to perform during the initial parse or checks needing more than just the JSON driver file. Examples:

    - Checking for vertex attribute arrays having the same number of elements
    - Checking for cycles in the node tree
    - Checking that mesh index buffer doesn't have out-of-bounds index values
    - Checking that mesh vertex data (animation data, ...) are in specified `min`/`max` bounds (if `min`/`max` is specified)
    - ... more?

    Some of these checks would need access to the data buffers. Besides passing the buffers I can imagine having a flags parameter allowing the user to specify what all to check. Failure in any of these would not be fatal, as the user code could be able to recover from most of these.

**Comment by jkuhlmann** [comment]
Thinking some more about this... Is this kind of extensive validation actually in the expected scope of this library?
If you'd like to see it, might it maybe make more sense to have it in a separate header file?

**Comment by zeux** [comment]
Yeah - I'm not sure where the boundary lies. My main goal for part 1 is to make sure that cgltf_parse is safe to call on an arbitrary input document - as in, you get *a* document without crashing :) This seems like a reasonable goal. Some minimal checking for the presence of specific required elements isn't too hard, but I don't know if that's where it should belong.

For part 2, it's not clear how far we can/should go. If a validator that catches most severe issues is possible to write in, say, 10% of the current codebase - then it seems reasonable to do it as part of the same header.

**Comment by zeux** [comment]
Worth noting is that I've been running into some issues with jsmn when fuzzing, we'll see how practical even part 1 is...

**Comment by zeux** [comment]
FWIW some of the checks above have landed - in particular, pointer values always “make sense” and are present if the spec says so. Node graph is guaranteed to be acyclic if you start traversal from root.

I found that some rules about required/optional pointers are not very intuitive - e.g. reading data from accessors basically requires to dereference accessor->buffer_view->buffer, but buffer_view can be NULL.

**Comment by mosra** [comment]
I also encountered such a file. Plays well with three.js, but tinygltf fails to import it due to missing buffer_view. Didn't investigate further but AFAIK that's to support `sparse` buffers for morph targets (or... compression extensions such as Draco? not sure). The file is here: https://threejs.org/examples/models/gltf/LittlestTokyo.glb (~4 MB), corresponding three.js example here: https://threejs.org/examples/webgl_animation_keyframes.html

**Comment by zeux** [comment]
I've looked at the GLTF spec and gathered an approximate list of things we can validate without accessing the buffer data. The list is pretty intimidating, we'll see how large the implementation for all of this is...	

- [ ] mesh->weights == NULL or mesh->weights_count == mesh->primitive->targets_count
- [ ] accessor sparse indices/values have to have sparse.count elts
- [ ] buffer view fits in size if stride is set
- [ ] buffer view fits in buffer if buffer is set
- [ ] index accessor refs buffer view with type indices
- [ ] index accessor has component type u8/u16/u32 & type scalar
- [ ] vertex accessor refs buffer view with type vertices (this is not in the spec??)
- [ ] skin has 1+ joints
- [ ] camera "type" field is consistent with data defn
- [ ] node weights == NULL or node weights match mesh target count
- [ ] node can have matrix or t/r/s but not both
- [ ] animation samplers have matching counts on input/output accessors
- [ ] load_buffers must check bin_size (should be >= buffer 0 size) & uri == NULL
- [ ] accessor.byteOffset and accessor.byteOffset + bufferView.byteoffset must be a multiple of component type size
- [ ] accessor.byteOffset + stride * (accessor.count - 1) + element_size must be <= bufferView.length
- [ ] all morph target accessors must have the same count as the accessors of the original primitive
- [ ] when the node contains skin, all mesh.primitives must contain JOINTS_0 and WEIGHTS_0 attributes.

**Comment by zeux** [comment]
Most of the above landed. I decided to limit the scope here to integrity checks that may affect application stability - will ignore checks like “does node have redundant set of transforms” because of that. I intend to implement the index value validation and close this.
