### ISSUE TITLE
Indices exceed number of vertices in .gltf files with .bin files

### ISSUE THREAD

**Issue by smokesugar** [jkuhlmann/cgltf#142]
I'm using cgltf to load models but have run into an issue with models with associated .bin files, where some indices exceed the number of vertices. The result is the below image.

![Broken](https://user-images.githubusercontent.com/54136924/109484762-ee9f3a00-7ad4-11eb-99f9-710537852795.PNG)

The image below is occurs when I take that model above and export it blender; the exported copy has no .bin file.
![NotBroken](https://user-images.githubusercontent.com/54136924/109485225-8735ba00-7ad5-11eb-8a44-cd53fa522300.PNG)

`cgltf_load_buffers` is being called.

**Comment by jkuhlmann** [comment]
Is this still an issue? Is there any chance you could share the your .gltf and .bin files?

**Comment by smokesugar** [comment]
Yes this is still an issue. Thanks for this library btw!

Here is the model:
https://drive.google.com/drive/folders/1rCStKQ57C7M5X98xEMO6nAvcqvWl4DHG?usp=sharing

**Comment by smokesugar** [comment]
It seems it is actually an issue with the mesh. It was autoconverted from sketchfab.
