### ISSUE TITLE
Errors opening files > 2GB in size

### ISSUE THREAD

**Issue by dtrebilco** [jkuhlmann/cgltf#151]
On Windows 64 bit, processing a file > 2GB in gltfpack, fails to open then fails to validate.

```c++
	if (file_size == 0)
	{
		fseek(file, 0, SEEK_END);

		long length = ftell(file);
		if (length < 0)
		{
			fclose(file);
			return cgltf_result_io_error;
		}

		fseek(file, 0, SEEK_SET);
		file_size = (cgltf_size)length;
```
size could be passed in to this function, but in this default code, long is signed 32 bit so does not return a correct value. 
A temp fix for Windows is
```c++
long long length = _ftelli64(file);
```

The second problem is cgltf_json_to_int() being used to read values stored in cgltf_size values, like buffer sizes and buffer offsets.

I locally created cgltf_json_to_size() that uses atoll() and replaced instances of cgltf_json_to_int() with it.

**Comment by jkuhlmann** [comment]
Thank you for the contribution @pixeljetstream !
Hmm, I guess neither of you has a good recommendation for a cross-platform way to approach `ftell()` and `fseek()`?

**Comment by pixeljetstream** [comment]
other than using various preprocessor defines to detect win32/64-bit no... but you could also document the problem for now as it's trivial to provide a custom loader function that takes care of that for users.

**Comment by zeux** [comment]
(on some Unix systems you can use `fseeko64` which is valuable on 32-bit systems if you don't intend to read the entire file into memory, but for cgltf I think it's sufficient to change this on Windows)
