### ISSUE TITLE
Material AlphaCutoff triggers validator warnings

### ISSUE THREAD

**Issue by manuelk** [jkuhlmann/cgltf#152]
When setting materials to opaque this writer causes the gltf validator to systematically throw this warning :

```
                "code": "MATERIAL_ALPHA_CUTOFF_INVALID_MODE",
                "message": "Alpha cutoff is supported only for 'MASK' alpha mode.",
                "severity": 1,
                "pointer": "/materials/0/alphaCutoff"
```

This is because the validator does not expect to see a value for the alpha_cutoff in the JSON dictionary in opaque modes
(see validator [code](https://github.com/KhronosGroup/glTF-Validator/blob/master/lib/src/base/material.dart#L66) here)

The simplest fix is probably to wrap the alpha cutoff output in a simple conditional :

```
static void cgltf_write_material(cgltf_write_context* context, const cgltf_material* material)
{
	cgltf_write_line(context, "{");
	cgltf_write_strprop(context, "name", material->name);
	cgltf_write_floatprop(context, "alphaCutoff", material->alpha_cutoff, 0.5f); // <--- make this conditional on alpha mode
```

**Comment by jkuhlmann** [comment]
Thanks and fixed!
