### ISSUE TITLE
Wide string support

### ISSUE THREAD

**Issue by jlacroixAMD** [jkuhlmann/cgltf#154]
Would it be possible to get const wchar_t* support for most functions that take string parameters as const char_t*?

Thanks.

**Comment by jkuhlmann** [comment]
Hi!
What are you mostly concerned about? Filenames? Or the actual JSON data?
Is what you're asking for part of the glTF spec?

**Comment by jlacroixAMD** [comment]
Yeah, it's just for the actual opening of the files. Everything in my environment is using a wide character set and having to do WString conversion to String just for the odd thing is a little inconsistent. 

That being said, it might be a moot point as the JSON parser I'm using also doesn't support wide characters which means I would also need to convert all the time when grabbing URI for buffers and images. I suppose this can be disregarded then in hindsight ...

**Comment by jkuhlmann** [comment]
I suppose you could still use `cgltf_parse()` and do the file opening and reading yourself. Then everything should work.
