### ISSUE TITLE
cgltf_free uses file release callback for base64 buffers

### ISSUE THREAD

**Issue by pezcode** [jkuhlmann/cgltf#158]
`cgltf_load_buffers` loads base64-encoded buffers with the `memory.alloc` callback, but `cgltf_free` frees *all* buffers with `file.release`. This is incorrect for cases where `memory.free` actually frees memory but `file.read` doesn't (e.g. using static embedded files), leading to a memory leak.

**Comment by jkuhlmann** [comment]
I've added a change in PR #160 that allows the library to track where the buffer data comes from. Does that help in your case?

**Comment by pezcode** [comment]
Yep, that fixes it. Appreciate the timely fix!
