### ISSUE TITLE
cgltf_parse_file can crash with custom file_open, should not call memory_free

### ISSUE THREAD

**Issue by pixeljetstream** [jkuhlmann/cgltf#159]
cgltf_parse_file crashes when the parsing fails with a custom read/release callback in use.
A pointer acquired from file_read cannot be passed to memory_free, but that is done here.

```
	void* file_data = NULL;
	cgltf_size file_size = 0;
	cgltf_result result = file_read(&options->memory, &options->file, path, &file_size, &file_data);
	if (result != cgltf_result_success)
	{
		return result;
	}

	result = cgltf_parse(options, file_data, file_size, out_data);

	if (result != cgltf_result_success)
	{
                // BUG? this should be file_release as the file_data was acquired by file_read
		memory_free(options->memory.user_data, file_data); 
		return result;
	}
```

**Comment by jkuhlmann** [comment]
Can you confirm that PR #160 would fix this?

**Comment by NeilBickford-NV** [comment]
To help out with this, I looked through all the occurrences of `options->file.release` and `options->memory.free` in cgltf.h. Assuming `file.release` and `memory.free` are not intended to be interchangeable (based on the issue #94 discussion [here](https://github.com/jkuhlmann/cgltf/issues/94#issuecomment-574286076)), then there may be two issues:

- `cgltf_parse_file()` gets a `file_data` pointer using `file.read` above. But this pointer is later passed to either `memory_free` [here](https://github.com/jkuhlmann/cgltf/blob/master/cgltf.h#L1149) if the parse fails, or passed to `file.release` in `cgltf_free()` [here](https://github.com/jkuhlmann/cgltf/blob/master/cgltf.h#L1898). (Looks like Johannes posted a fix right as I was writing this - I'll test it out!)
- When reading buffers, buffers stored in files are read using `file.read` [here](https://github.com/jkuhlmann/cgltf/blob/master/cgltf.h#L1195), but Base64 buffers are decoded to a buffer allocated using memory.alloc` [here](https://github.com/jkuhlmann/cgltf/blob/master/cgltf.h#L1209). Both of these appear to be released using `file.release` in `cgltf_free()` [here](https://github.com/jkuhlmann/cgltf/blob/master/cgltf.h#L1671) (there's a special case for the .glb binary section which gets handled correctly!)

Also - thanks very much; I'll test out the PR and hopefully it should fix the `cgltf_parse_file()` issue!

**Comment by jkuhlmann** [comment]
Funny that this all comes up now. Your second bullet point is the same as #158, is that correct?

**Comment by NeilBickford-NV** [comment]
Oh, yep, looks like that is indeed the same issue!

Also, I can confirm that PR #160 fixes the `cgltf_parse_file()` issue with custom file callbacks and invalid glTF files - thank you, Johannes!

**Comment by jkuhlmann** [comment]
I think in that case we don't have much of a choice except for tracking where the data comes from. I've added another change to #160. Does that help?

**Comment by pixeljetstream** [comment]
we didn't run into #158 but your fixes looks good
