### ISSUE TITLE
_ftelli64 does not compile on Windows when using zig cc (clang, mingw64)

### ISSUE THREAD

**Issue by michal-z** [jkuhlmann/cgltf#162]
I hit a compile error when compiling with zig cc - ```_ftelli64``` is msvc thing so the check for it should be:
```
#if defined(_WIN32) && defined(_MSC_VER)
```

Note.
zig cc by default uses clang and mingw64 so it defines ```__clang__``` and ```__GNUC__```.
On the other hand, cl-clang on Windows defines ```__clang__``` and ```_MSC_VER```.

**Comment by floooh** [comment]
FYI: at least on macOS the regular ftell() function returns a 64-bit value (long int). I tested by creating a 6000*1024*1024 bytes file and then:

```c
    FILE* fp = fopen("file.bin", "rb");
    fseek(fp, 0, SEEK_END);
    long int pos = ftell(fp);
    fclose(fp);
    printf("size: %ld\n", pos);
```

This prints:
```
size: 6291456000
```
I'd expect on Linux this also works, and that it's just Windows which is the outlier.

**Comment by michal-z** [comment]
@floooh Thanks for the info. Yes, this Windows issue only.

**Comment by michal-z** [comment]
Turned out that this is a zig cc bug/omission. zig cc uses mingw-w64 and mingw-w64 has implementation for _ftelli64, but zig cc did not expose it. This will be fixed on the zig cc side.
