### ISSUE TITLE
Proposal for a simpler attribute structure

### ISSUE THREAD

**Issue by zeux** [jkuhlmann/cgltf#21]
Right now the structure of attribute data is as follows:

```
typedef struct cgltf_attribute
{
	cgltf_attribute_type name;
	cgltf_accessor* data;
} cgltf_attribute;

typedef struct cgltf_morph_target {
	cgltf_attribute* attributes;
	cgltf_size attributes_count;
};

typedef struct cgltf_primitive {
	cgltf_attribute* attributes;
	cgltf_size attributes_count;
};
```

This correctly reflects GLTF spec, but has two issues:
- It's inconvenient to consume - you basically need to implement helper functions that find an attribute by type
- It results in deeply nested structures for primitives and morph targets, requiring more allocations.

I was thinking that we can switch to an alternative structure - if `cgltf_attribute_type` enum had a `count` entry, we could instead use:

```
typedef struct cgltf_morph_target {
	cgltf_accessor* attributes[cgltf_attribute_type_count];
};

typedef struct cgltf_primitive {
	cgltf_accessor* attributes[cgltf_attribute_type_count];
};
```

This fixes both issues with the current approach, however it makes it impossible to support "flexible" attribute types - that is, attribute types with names not recognized by the current spec or any extensions. For example, if you export a mesh with more UV sets than 2, I'm guessing you'd get `TEXCOORD_2` or `TEXCOORD_3`. Right now we could support this in a generic fashion by adding `char* custom` to `cgltf_attribute` but if we used arrays we'd need to extend an enum. However, extending an enum is easy :)

Thoughts? I'm mildly leaning towards reworking this to a flat array but not 100% sure.

**Comment by mosra** [comment]
Personally I would rather have the attributes more flexible at the cost of the access being less convenient. (Coincidentally, I'm just now reworking mesh support [in my engine](https://magnum.graphics) to support arbitrary attributes and thought glTF would be the first format with such support.)

To avoid the nested allocations, what about this?

```c
typedef struct cgltf_primitive {
	cgltf_attribute attributes[cgltf_attribute_type_max_count];
	cgltf_size attributes_count;
};
```

As in, you still have to go through all attribs to find one by name, but at least it's localized memory access. The total amount of attributes is still limited by the enum, but could be set a bit higher than what glTF currently supports (so not 8, but let's say 16 or something else that aligns nicely). For extreme cases, the `cgltf_attribute_type_max_count` *still* needs to be extended, but it's a much rarer chance to hit this limit.

**Comment by zeux** [comment]
I'd probably be reluctant to change the attributes to a fixed-size array since that doesn't simplify user interface and only simplifies some internals. There's a version that simplifies user interface but still allows for custom attributes which would involve *adding* the array I've proposed to existing structure for easy lookup but keeping existing structures as well. Of course that'd mean we're getting a slightly more complex internal structure :(

I was basically hoping to kill two birds with one stone - but yeah, lack of custom attributes could be unfortunate. Do you have any data on custom attributes that can be produced by GLTF-aware tools that cgltf currently doesn't recognize?

**Comment by mosra** [comment]
I have an example, but it's all NDA'd, sorry :/ Created using a patched version of the Blender glTF exporter and then imported with tinygltf.

> *adding* the array I've proposed to existing structure for easy lookup but keeping existing structures as well. Of course that'd mean we're getting a slightly more complex internal structure :(

In my generalized case I ended up providing a helper function that returns the real attribute index for e.g. "get me the second texture coordinate attribute". It's a "slow" linear lookup, but I don't think that matters much in this case -- better than forcing users to implement this each time on the app side. 

Also thought about ordering the attribs (so e.g. first is always the position, then normals, ...), but that didn't really seem to simplify things much.

**Comment by zeux** [comment]
I didn't mean the specific .gltf file, I meant the name/purpose of the attribute.

**Comment by mosra** [comment]
That's the thing, the particular name/purpose is NDAd... 

But besides that -- if that helps -- we have some models that use three and more UV sets, each of them animated in a different way to achieve various effects (like KHR_texture_transform, but with animated values (again a custom thing)).

**Comment by zeux** [comment]
Thinking about this more, I don’t want to give up custom names. Plan atm is to change attribute name to char* and introduce attribute_accessors array that can be used to easily fetch builtin attributes. The char* makes the memory layout even deeper but I don’t think there’s a good way around it.

**Comment by mosra** [comment]
I know I'm stating the obvious, but why not `#define` some max size (so users can override it, if needed) and have `char attribute_name[MAX_PROPERTY_NAME_SIZE]`? Then failing the parse (or plainly ignoring the attribute) if the name is too big.

Crazy idea: having the name `char*` point to the original file memory (in case the file is loaded from memory), together with a size? Something similar could be done for arbitrary extensions and `extra` fields.

**Comment by zeux** [comment]
Yeah the latter is what I might do for extra or for extensions. Seems like the core structures should be more C like though.
