### ISSUE TITLE
Support for EXT_texture_webp

### ISSUE THREAD

**Issue by hannojg** [jkuhlmann/cgltf#248]
Hello, 

I understand that not all EXT_ are supported yet. I am particularly interested in support for the `EXT_texture_webp` extension.
Do you want to support this extension in cgltf? If so, I could check to contribute 😊

**Comment by jkuhlmann** [comment]
Hi!
This one seems pretty straightforward and could probably easily be accessed through the generic extension pointers. However, if you feel like contributing it, I'll be happy to merge it. 😀

**Comment by bobbens** [comment]
Implemented in #253, seems to work here.

**Comment by hannojg** [comment]
Thanks for the work guys!
