### ISSUE TITLE
Reading glTF binary files in GLB format

### ISSUE THREAD

**Issue by native-engine** [jkuhlmann/cgltf#249]
Does cgltf allow you to read binary glTF files? If yes, can I see an example somewhere?

**Comment by zeux** [comment]
`cgltf_parse_file` (see example in the README) will automatically handle .glb files the same as .gltf; calling `cgltf_load_buffers` after that will associate internal buffer pointers with the embedded binary data which will lead to other accessor helpers to work transparently.

**Comment by native-engine** [comment]
Got it, thank you very much!
