### ISSUE TITLE
Incorrect parsing of numeric values from glb file

### ISSUE THREAD

**Issue by native-engine** [jkuhlmann/cgltf#250]
When importing models from a **glb** file, properties **cgltf_float** of class **cgltf_accessor** such as **0.9999997019767761** and **0.9999993443489075** are parsed as **0**, and **-0.9999990463256836** as **-0**:

![Screenshot_20240329_145055](https://github.com/jkuhlmann/cgltf/assets/18296438/70fec65f-1517-49da-b932-b6d7c380aa63)

I already wrote to Khronos developers about why their plugin exports 1 and -1 values from Blender 3D so incorrectly, but they replied that this is a flaw in the JSON parser, not in their plugin.

I'm attaching some of my code:
```
if (data->accessors[j + iBufferView].has_min) ParsingMesh->vMin = glm::vec3(data->accessors[j + iBufferView].min[0], data->accessors[j + iBufferView].min[1], data->accessors[j + iBufferView].min[2]);
if (data->accessors[j + iBufferView].has_max) ParsingMesh->vMax = glm::vec3(data->accessors[j + iBufferView].max[0], data->accessors[j + iBufferView].max[1], data->accessors[j + iBufferView].max[2]);
```
and the textual analog of its glb file: [model.gltf.json](https://github.com/jkuhlmann/cgltf/files/14799945/model.gltf.json).

**P.S.** Parser TinyGLTF exports all numeric values correctly, but: https://github.com/syoyo/tinygltf/issues/483...

**Comment by zeux** [comment]
My guess would be that you're not using the English locale; cgltf uses stdlib functions like strtod for parsing, which are locale sensitive. Normally the locale would default to C but maybe something in your application is setting it to system; using `setlocale(LC_ALL, "C");` before calling cgltf_parse could fix this.

**Comment by native-engine** [comment]
The script gave a syntax error next to the unexpected token "LC_ALL," and this can't be done via C++ so I don't have to write a bash script?

**Comment by native-engine** [comment]
The script generated a syntax error next to the unexpected marker "LC_ALL," but can't we solve this issue via C++ so that we don't have to write a script separately???

**Comment by native-engine** [comment]
Thank you very much for the idea, added the following code and the parsing became correct:
```
#include <clocale>
* * *
setlocale(LC_ALL, "C");
```
