### ISSUE TITLE
Correct handling of non-required attributes that are non-zero

### ISSUE THREAD

**Issue by jpaver** [jkuhlmann/cgltf#42]
First of all thanks for the great library and all the active work that is going on here. The library was super easy to integrate and works like a charm. 

Second, I just wanted to file an issue I discovered ;)

If the primitive mode is not specified in serialized json, the mode does not correctly take on the default of '4' (see 'https://github.com/KhronosGroup/glTF/tree/master/specification/2.0' look for 'primitive.mode').  

I find this often happens with the khronos blender GLTF exporter, and you'll see something like the following in the source .gltf file (notice no explicit mode in there):

```
            "name" : "Cylinder.001",
            "primitives" : [
                {
                    "material" : 0,
                    "indices" : 29,
                    "attributes" : {
                        "POSITION" : 25,
                        "NORMAL" : 21,
                    }
                }]
```

My local fix was to put this line into cgltf_parse_json_primitive before entering the main loop:
	out_prim->type = cgltf_primitive_type_triangles;

I've verified this does the trick for me. Unfortunately, I'm not setup for PRs right now - but hopefully someone else can get this in.

Eyeballing the code in a few places, it looks like this may represent a class of issues for a few other attribute where the default is non-required and the value non zero. eg. sampler.wrapS, sampler.wrapT, so it may be worth doing a general pass over the spec to uncover more.

Thanks again
-Justin

**Comment by jkuhlmann** [comment]
Looks like the ones you mentioned were actually the ones missing. At least I couldn't find any others. This is fixed by PR #44.
