### ISSUE TITLE
Provide utility for data conversion?

### ISSUE THREAD

**Issue by prideout** [jkuhlmann/cgltf#46]
This is a proposal for a utility function in the same vein as `cgltf_node_transform_world` and `cgltf_node_transform_local`.

Ideally all glTF buffers are blobs that get sent to the GPU and never need CPU-side processing.  However in practice clients often need to convert some of the buffers (especially animation and skinning data) into simple arrays of 32-bit floats to avoid dealing with normalized integers, stride, etc. on the CPU.

The prototype could be:
`cgltf_result cgltf_accessor_convert(const cgltf_accessor* in_data, cgltf_float* out_floats);`

**Comment by prideout** [comment]
I coded this up, I can make a PR after I add tests and support for sparse accessors.

**Comment by zeux** [comment]
The idea is interesting. I'm wondering if it's better to do something like

```
void cgltf_accessor_read(const cgltf_accessor* accessor, size_t index, cgltf_float* out, size_t out_size);
```

so that the caller doesn't need to allocate a large buffer? Or maybe something like

```
cgltf_float cgltf_accessor_read_float(const cgltf_accessor* accessor, size_t index, size_t component);
cgltf_int cgltf_accessor_read_int(const cgltf_accessor* accessor, size_t index, size_t component);
```

This can then be used to parse index buffers, vertex buffers, bone indices etc. - it can return 0 on errors (all validation could happen in `cgltf_validate`). I definitely end up writing something along these lines whenever I need to parse GLTF files.

**Comment by jkuhlmann** [comment]
@prideout Something like this would be very welcome.

@zeux's first suggestion (`void cgltf_accessor_read(const cgltf_accessor*, size_t, cgltf_float*, size_t)`) looks the most practical to me. It probably wouldn't be such a big difference from your implementation, @prideout?
The functions for reading one value at a time would presumably have quite a big function call overhead if you're handling lots of data.

**Comment by prideout** [comment]
These are good ideas!  Taking it a bit further, the API should perhaps take a range of indices, so that clients can either use them either way: one-at-a-time or a batch.

I also like the idea of providing a to-integer variant, which I had to write internally anyway in order to support sparse accessors.

**Comment by mosra** [comment]
In my case the engine is already handling all of this, would it be possible to have this in a separate header, since it's not an essential functionality and thus would be a dead weight to some users? 

It's not a problem with the existing `cgltf_node_transform_world()` etc. APIs, but here I can imagine it could grow pretty large. Especially considering future glTF versions are expected to have more complex data packing options, use of half-floats etc.

**Comment by zeux** [comment]
My understanding is that right now this function should be on the order of 20 lines of code if we don't need to handle sparse data?

Re: "range of indices", I really do believe we should keep this API as simple as possible, hence my later suggestion about one-at-a-time. Function call overhead wouldn't matter in a typical single-file-use scenario where cgltf.h implementation is included into a single source file using it, and I'm not sure how substantial the reduction is if you just consider reading in short bursts (it's typical to read 2 floats per texcoord for example).

I'd suggest limiting the implementation to a single returned value in the interest of interface simplicity and checking the overhead with inlining disabled.

**Comment by prideout** [comment]
Agreed with @zeux, this isn't much code and it gets optimized out if you don't use it.  In fact supporting sparse accessors isn't a big deal.  I'm not quite ready to make a PR because I haven't tested it well yet, but feel free to take a sneak peak at b2ca29b.

**Comment by prideout** [comment]
@zeux, I've come around to your point of view regarding index vs range.  Simplicity rules!  The only thing I'm unsure about is whether to return individual components (as I've done in my initial implementation) or to return the entire element (e.g. all 9 floats of a mat3) into an output pointer.

I'm leaning towards an output pointer; this is especially useful for the [three padded matrix types](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#data-alignment) and it would still be a very simple API (same number of args as before).

**Comment by jkuhlmann** [comment]
I agree that it would be more convenient to output a complete element. Otherwise it would get kind of weird how you’d have to skip indices to skip the padding.
