### ISSUE TITLE
cgltf_calc_size is incorrect for certain matrix types

### ISSUE THREAD

**Issue by prideout** [jkuhlmann/cgltf#47]
Currently validation computes element size with a simple `component-size * num-of-components` which I think isn't quite right for the three corner cases highlighted here:

https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#data-alignment

**Comment by jkuhlmann** [comment]
Should be fixed by commit 8cd1946d415cc37e7766d92f30211ae65f6f4d61.
