### ISSUE TITLE
Image and Buffer read

### ISSUE THREAD

**Issue by amadlover** [jkuhlmann/cgltf#49]
Hello please look at providing image and buffer data as part of cgltf_data. 

Having said this, Is the image and buffer data part of cgltf_data when reading a GLB file.

Thank you!!!

**Comment by zeux** [comment]
`cgltf_load_buffers` can be used to load buffer data.

There's currently no way to load image data; OTOH it's not clear what exactly is the best way to do this - loading raw encoded image data in, say, PNG format as a set of bytes isn't useful, and adding a dependency on a third-party image loader is against the dependency policy of this library. So it'll have to be some sort of callback API, but the callback has to be able to load both from memory (in case image data is embedded) and from file.

**Comment by amadlover** [comment]
Hello, please consider embedding third party image reading sources, like jsmn source embedded currently.

This is the only reason why I am stuck with using tinygltf, the compile time for that one file which uses tinygltf is more than the entire solution combined.

**Comment by prideout** [comment]
Hi @amadlover, you can easily use a third-party image loader in combination with cgltf, there is nothing preventing you from doing that yourself in the application.

For example, in Filament we use cgltf combined with stb_image.

**Comment by amadlover** [comment]
@prideout thank you for pointing it out.
