### ISSUE TITLE
Access to extra data in glb file

### ISSUE THREAD

**Issue by dradix** [jkuhlmann/cgltf#50]
Hello,

It would be great if cgltf provided a way to access the extra data in a glb file. Like the information is written here for example https://github.com/opensourceBIM/GltfSerializers/blob/master/Gltf/src/org/bimserver/gltf/BinaryGltfSerializer2.java#L425
Do you think is this an easy feature to implement?

Thank you very much for your attention.

**Comment by amadlover** [comment]
Proving all the content present in the GLB / gltf file to the calling program would be ideal

**Comment by jkuhlmann** [comment]
Can you provide a sample glTF or glb file that contains typical extras data?

**Comment by nxrighthere** [comment]
This feature is very useful for game engines where any object can contain various extra data.

A random example:
```json
{
    "cameras" : {
        "perspectiveCamera_id" : {
            "name" : "MainCamera",
            "perspective" : {
                "aspectRatio" : 1.77,
                "yfov" : 0.7854,
                "zfar" : 1000,
                "znear" : 1
            },
            "type" : "perspective",
            "extras" : {
                "name" : "PerspectiveCamera",
                "hash" : "C1BE5A6944942D071CCE265D2089C0A7",
                "uuid" : "82e3597e-76c9-11e9-8f9e-2a86e4085a59",
                "scripts" : "main_camera.c;player_camera"
            }
        },
    }
}
```

**Comment by jkuhlmann** [comment]
Thanks for the example! I agree that it’s very useful. 

At the moment, I’m just as a first step looking for sample assets to come up with a design and subsequently be able to test.

**Comment by nxrighthere** [comment]
Here: [Sample.zip](https://github.com/jkuhlmann/cgltf/files/3181443/Sample.zip)

**Comment by zeux** [comment]
I'm interested in this as well but not sure what the design should be. The complexity is that "extra" can be completely arbitrary JSON. We could make a generic JSON API (that seems heavy-handed), expose jsmn token range (that seems odd) or return a character range in the original JSON document and require user to parse (that doesn't seem useful). Great choices all around! 😜 

My specific use case is I want to just preserve the extra information in the node without modifying it, but I'd imagine that it's more common to have to parse it out.

**Comment by zeux** [comment]
Oh also "extras" can be in basically every single node, so we'll need to modify most structs to include this. Maybe as a first blush we could have `cgltf_extras` struct that has a list of key/value string pairs, as well as a full JSON dump for more complex usecases?

**Comment by nxrighthere** [comment]
Maybe we can just pass data to the application as is (string/bytes?), and let the user choose how to handle it (JSON/YAML/TOML/custom)?

**Comment by jkuhlmann** [comment]
The approaches we have here are also pretty much what I’ve come up with. Additionally, we could also do callbacks for extra data so that the user can process it to what’s required. 
But I don’t really like that either. My current favorite is handing out the character range I think as it has the smallest overhead and the greatest flexibility.

**Comment by zeux** [comment]
Maybe we can start with just the character range, and then if necessary we could provide helpers to parse that separately (cgltf_parse_extra that could take a callback, or return a list of key-value pairs, or something simple).

**Comment by jkuhlmann** [comment]
The first part is in PR #62. Did I miss anything?

**Comment by zeux** [comment]
I've lightly tested this and it works for me.

**Comment by jkuhlmann** [comment]
That's good enough then for now. If anyone needs anything more let me know.
