### ISSUE TITLE
Consider exposing cgltf_load_buffer_base64

### ISSUE THREAD

**Issue by prideout** [jkuhlmann/cgltf#51]
For Filament's WebGL build we were able to use cgltf as-is with this one exception.

We easily wrote our own alternative to `cgltf_load_buffers` (since the filesystem does not exist), but we didn't want to write our own base64 decoder, so we had to publicize the one in our local copy of cgltf.

**Comment by jkuhlmann** [comment]
That totally makes sense. Should be fixed by a6b807790cc7a92cbbc3c106530e97c8d14656e5.

**Comment by prideout** [comment]
Thanks so much!
