### ISSUE TITLE
Proposal for cgltf_write.h

### ISSUE THREAD

**Issue by prideout** [jkuhlmann/cgltf#52]
I've made a good bit of progress on a tentative [`cgltf_write.h`](https://gist.github.com/prideout/c0d864f5cbd197f3effa0f7a2a1a03a6).  It includes `cgltf.h` in order to re-use the POD structures.

This is similar to how `stb_image_write.h` is a complement to `stb_image.h`.

I will keep working on it, and I will make a PR when I'm done, but please feel free to steer me on a course.

**Comment by prideout** [comment]
One issue is how to deal with the free / release for all the lists in structs.  Instead of profferring methods that do this, I think we should simply let the client be responsible for allocating and freeing.  The writer simply consumes the struct and dumps out JSON.

It might be interesting to support GLB too...but in the future.  :)

**Comment by jkuhlmann** [comment]
Looking great already!

I agree the memory management is tricky. On the one hand, it's easy for the user to make a mistake. On the other hand, we can't assume they allocated the memory in a given way. :thinking: 

Do you think it would  be possible to decouple the writing from using the `FILE*` functions? Instead, we could offer a way to write to a buffer and then build the file functionality on top, just like the reading counterpart does it.

**Comment by prideout** [comment]
Ah, that's a good idea, yes I can replace my calls to `fprintf` with `snprintf` etc.  This would allow the writer header to have two entry points: `cgltf_write_file()` and `cgltf_write()` where the latter is a lower level API.  Similar the existing `parse()` / `parse_file()`.  What do you think?

**Comment by jkuhlmann** [comment]
That would be perfect in my opinion.
I'm just not sure how to easily determine the required size for the string/buffer upfront. Do you have an idea?

**Comment by prideout** [comment]
Maybe the top-level `cgltf_write` function will return bytes written.  If it is passed a null pointer, it  returns the number of bytes it *would* write.

Then, best practice would be for clients to call the function twice, once to determine size, once to dump out the tree.

**Comment by jkuhlmann** [comment]
Sounds good. Then you'd have the option to call it with a sufficiently large buffer (if you can estimate/know how big the buffer is going to be) or call it twice. :+1:
