### ISSUE TITLE
Attribute types maybe wrong

### ISSUE THREAD

**Issue by pjako** [jkuhlmann/cgltf#64]
I just played a bit around with cgltf and used the box sample from the sample repo:
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Box/glTF-Binary

For attributes I wanted to rely on its type but is seems to be wrong:

![attributeTypewrong](https://user-images.githubusercontent.com/1504380/59920451-d5527900-942a-11e9-9f6e-d1243ee2f47d.png)

**Comment by jkuhlmann** [comment]
That's weird. Did maybe something go wrong?

Seems to work here:
![Bildschirmfoto_2019-06-24_23-29-35](https://user-images.githubusercontent.com/2406700/60053394-0c998200-96d8-11e9-8e96-47ed430a3e47.png)

**Comment by jkuhlmann** [comment]
Cannot reproduce and got no further feedback.
