### ISSUE TITLE
Why is cgltf_calc_size not exposed

### ISSUE THREAD

**Issue by sjfricke** [jkuhlmann/cgltf#77]
I realize that the small number of API functions exposed is a feature, but when trying to get strides and size for my `primitive.attributes.accessor` I am finding myself in need of the call. Unless there is another way that I am missing

**Comment by jkuhlmann** [comment]
Actually, it's not exposed because that's exactly what it's used for internally. The stride for accessors should already be set. And for the size you should be able to use the size from the buffer view.

Does that help?

**Comment by sjfricke** [comment]
... `data->accessors[i].stride = cgltf_calc_size(...`

sorry, idk how I didn't realize there was a stride value there. I was reviewing the [glTF spec](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#accessor) and didn't catch you have an extra field in `cgltf_accessor`

thanks and sorry for noise

**Comment by jkuhlmann** [comment]
No worries.
Thanks for the feedback though, I suppose this means we could improve our documentation. :-)
