### ISSUE TITLE
Best way to deal with dummy buffers?

### ISSUE THREAD

**Issue by zeux** [jkuhlmann/cgltf#89]
For the sake of this issue, "dummy" buffer is a buffer with no data (cgltf_buffer::data == NULL).

This can happen in one of the following ways:

- `cgltf_load_buffers` wasn't called on the file
- File has buffer declaration with no `uri`, and the buffer isn't part of the GLB file.

There was some semi-recent discussion about the intended semantics of the latter, please refer to https://github.com/KhronosGroup/glTF/pull/1686 (and linked issue 1684) for details. The TL;DR is that the expectation is that buffers with no `uri` are valid, but if they are referenced by the scene, their behavior is left to extensions / future glTF versions to define.

In cgltf, this comes up as a very simple problem - a file where a dummy buffer is referenced by an accessor loads fine, validates (via `cgltf_validate`) fine, but then `cgltf_accessor_*` functions crash when dereferencing a NULL pointer.

I can see a few options to resolve this.

1. Add a `data == NULL ` check to all `cgltf_accessor_*` functions, and return `false`. This seems unambiguously good, but doesn't seem satisfactory - it may obscure the error (such as forgetting to load buffer data), and it would be nice to be able to call some function up-front to not have to deal with this. Additionally, `cgltf_accessor_read_index` can't fail, so it must return 0.

2. Change `cgltf_validate` to return "invalid data" when buffer data is NULL. The problem with this is that this makes it mandatory to call validate on a file with in-memory contents, which may not fit some use cases well.

3. Move buffer data validation into `cgltf_validate_buffers` or some such, and in that function require that data is non-NULL. This also cleans up a weird ambiguity with validate - it's currently safe to call it before or after `cgltf_load_buffers`, but if you call it before, the buffer contents isn't validated.

4. Add a bitmask `flags` to `cgltf_validate` where we can specify what parts of data to validate - initially we could have a single bit mask, "validate buffers", that will effectively do what (3) suggests, but within the same function.

Opinions? Any options I am missing? I am leaning to doing 1 anyway, and doing either 3 or 4, with weak preference for 4 since that allows us to incorporate more optional checks in the future.

**Comment by zeux** [comment]
I tried options 3/4 and they work fine but unfortunately they effectively block the use of the validation functions in tandem with any cases where the data *is* provided by an extension, which is somewhat unsatisfactory. Additionally, in basic cases, it's easy enough to avoid the problem with the following function:

```
bool validateAccessors(cgltf_data* data)
{
	for (size_t i = 0; i < data->accessors_count; ++i)
	{
		cgltf_accessor* accessor = &data->accessors[i];

		if (accessor->buffer_view && accessor->buffer_view->buffer->data == NULL)
			return true;

		if (accessor->is_sparse)
		{
			cgltf_accessor_sparse* sparse = &accessor->sparse;

			if (sparse->indices_buffer_view->buffer->data == NULL)
				return true;
			if (sparse->values_buffer_view->buffer->data == NULL)
				return true;
		}
	}

	return false;
}
```

So perhaps for now it's sufficient to implement 1 to deal with this...

**Comment by jkuhlmann** [comment]
I see you were quicker implementing this than me getting back to you with my thoughts. :-) I think this is a very good solution.
